### ISSUE TITLE
APSIM cloud service?

### ISSUE THREAD

**Issue by UKum540** [APSIMInitiative/APSIM.Cloud#16]
Hi,
I am running an optimization using 'r for both APSIM classical version and APSIM-NG. I have a large number of simulations. To run these simulations quickly I am interested to know more about the APSIM cloud service; service charges,  etc. It will be great if you could provide an estimation as well of th time it could to run,for example, 300,000 simulations with daily outputs for APSIM7.9 and APSIM-NG. 
Thanks

**Comment by hol430** [comment]
@hol353 are you able to answer this one? I'm not even sure what's in this repo

**Comment by hol353** [comment]
This APSIM 'cloud' service is no longer operational and was only meant for internal use. We don't offer a cloud service for running APSIM simulations.

**Comment by UKum540** [comment]
Thanks for the reply.
